add_newline = false
format = """
$env_var\
$conda\
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status
$character
"""

[env_var.CONDA_EXE]
format = '🐍'

[conda]
format = '\($environment\)'

[time]
disabled = false
format = '\[[$time]($style)\] '
style = "yellow"

[directory]
style = "green"
truncation_length = 6
truncation_symbol = ".../"
truncate_to_repo = false

[git_branch]
style = "purple"
symbol = ""

[git_commit]
style = "purple"

[git_status]
untracked = ""

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](bold red)'
