add_newline = false
format = """
$cmd_duration\
$custom\
$conda\
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status
$character
"""

[cmd_duration]
format = """⏱  took [$duration]($style)
"""

[custom.conda-shell]
when = 'test "$(env | rg PS1=conda-shell)"'
format = '\(conda-shell\) '

[conda]
format = '\($environment\) '
ignore_base = false

[time]
disabled = false
format = '\[[$time]($style)\] '
style = "yellow"

[directory]
style = "green"
truncation_length = 6
truncation_symbol = ".../"
truncate_to_repo = false

[git_branch]
style = "purple"
symbol = ""

[git_commit]
style = "purple"

[git_status]
untracked = ""

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](bold red)'
