##################################################
[[language]]
name = "python"
language-servers = ["pylsp"]

[language.formatter]
command = "black"
args = ["-", "--quiet"]

[language-server.pylsp.config.pylsp]
configurationSources = ["flake8"]

[language-server.pylsp.config.pylsp.plugins]
flake8 = { enabled = true }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }

##################################################
[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "latex"
language-servers = ["texlab", "snippets-ls-latex"]

[language-server.snippets-ls-latex]
command = "snippets-ls"
args = ["-config", "/home/perlinm/nix/dotfiles/snippets-latex.json"]
