##################################################
[[language]]
name = "python"

[language.formatter]
command = "black"
args = ["-", "--quiet"]

[language.config.pylsp]
configurationSources = ["flake8"]

[language.config.pylsp.plugins]
flake8 = { enabled = true }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }

##################################################
[[language]]
name = "nix"
formatter = { command = "nixfmt" }

##################################################
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language.language-server]
command = "" # disable TOML language server due to time-out bug
